import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import s from "../styles/Home.module.css";
import construction from "/public/construction.png";

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Kevin Collazos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <Image src={construction} width={500} height={500} />
        <h1>Page under construction. Coming soon...</h1>
      </main>
    </div>
  );
};

export default Home;
